import type { Metadata } from "next";
import { Suspense } from "react";
import { Poppins } from "next/font/google";

import "./globals.css";
// @ts-ignore: CSS module has no type declarations in this project
import "react-date-range/dist/styles.css";
// @ts-ignore: CSS module has no type declarations in this project
import "react-date-range/dist/theme/default.css";
import FullScreenLoader from "@/components/FullScreenLoader";
import LoadingOverlay from "@/components/LoadingOverlay";
import Providers from "@/app/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Cooncierge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Suspense fallback={<FullScreenLoader />}>
          <Providers>
            <LoadingOverlay />
            {children}
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
