import type {
  AmountSectionValue,
  SellingPriceEntry,
} from "@/components/AmountSection";
import type {
  RescheduledAmountValue,
  RescheduledSellingPriceEntry,
} from "@/components/RescheduledPriceSection";

export const toRescheduled = (
  src: Partial<AmountSectionValue>,
): RescheduledAmountValue =>
  ({
    oldCostPrice: src.costprice,
    oldCostCurrency: src.costCurrency,
    oldCostRoe: src.costRoe,
    oldCostInr: src.costInr,
    oldCostNotes: src.costNotes,
    additionalCostPrice: src.costRefundAmount,
    additionalCostCurrency: src.costRefundCurrency,
    additionalCostRoe: src.costRefundRoe,
    additionalCostInr: src.costRefundInr,
    additionalCostNotes: src.costRefundNotes,
    oldSellingPrice: src.sellingprice,
    oldSellingCurrency: src.sellingCurrency,
    oldSellingRoe: src.sellingRoe,
    oldSellingInr: src.sellingInr,
    oldSellingNotes: src.sellingNotes,
    additionalSellingPrice: src.sellingRefundAmount,
    additionalSellingCurrency: src.sellingRefundCurrency,
    additionalSellingRoe: src.sellingRefundRoe,
    additionalSellingInr: src.sellingRefundInr,
    additionalSellingNotes: src.sellingRefundNotes,
    oldVendorBasePrice: src.vendorBasePrice,
    oldVendorBaseCurrency: src.vendorBaseCurrency,
    oldVendorBaseRoe: src.vendorBaseRoe,
    oldVendorBaseInr: src.vendorBaseInr,
    oldVendorBaseNotes: src.vendorBaseNotes,
    additionalVendorBasePrice: src.vendorInvoiceRefundAmount,
    additionalVendorBaseCurrency: src.vendorInvoiceRefundCurrency,
    additionalVendorBaseRoe: src.vendorInvoiceRefundRoe,
    additionalVendorBaseInr: src.vendorInvoiceRefundInr,
    additionalVendorBaseNotes: src.vendorInvoiceRefundNotes,
    oldVendorIncentiveReceived: src.vendorIncentiveReceived,
    oldVendorIncentiveCurrency: src.vendorIncentiveCurrency,
    oldVendorIncentiveRoe: src.vendorIncentiveRoe,
    oldVendorIncentiveInr: src.vendorIncentiveInr,
    oldVendorIncentiveNotes: src.vendorIncentiveNotes,
    additionalVendorIncentive: src.chargebackAmount,
    additionalVendorIncentiveCurrency: src.chargebackCurrency,
    additionalVendorIncentiveRoe: src.chargebackRoe,
    additionalVendorIncentiveInr: src.chargebackInr,
    additionalVendorIncentiveNotes: src.chargebackNotes,
    oldCommissionPaid: src.commissionPaid,
    oldCommissionCurrency: src.commissionCurrency,
    oldCommissionRoe: src.commissionRoe,
    oldCommissionInr: src.commissionInr,
    oldCommissionNotes: src.commissionNotes,
    additionalCommissionPaid: src.commissionRefundAmount,
    additionalCommissionCurrency: src.commissionRefundCurrency,
    additionalCommissionRoe: src.commissionRefundRoe,
    additionalCommissionInr: src.commissionRefundInr,
    additionalCommissionNotes: src.commissionRefundNotes,
    rescheduledSellingPrices: src.sellingPrices?.map(
      (sp): RescheduledSellingPriceEntry => ({
        oldSellingPrice: sp.sellingprice,
        oldSellingCurrency: sp.sellingCurrency,
        oldSellingRoe: sp.sellingRoe,
        oldSellingInr: sp.sellingInr,
        oldSellingNotes: sp.sellingNotes,
        additionalSellingPrice: sp.sellingRefundAmount,
        additionalSellingCurrency: sp.sellingRefundCurrency,
        additionalSellingRoe: sp.sellingRefundRoe,
        additionalSellingInr: sp.sellingRefundInr,
        additionalSellingNotes: sp.sellingRefundNotes,
      }),
    ),
  }) as RescheduledAmountValue;

export const fromRescheduled = (
  r: RescheduledAmountValue,
  existing?: AmountSectionValue,
): AmountSectionValue =>
  ({
    ...(existing ?? {}),
    costprice: r.oldCostPrice,
    costCurrency: r.oldCostCurrency,
    costRoe: r.oldCostRoe,
    costInr: r.oldCostInr,
    costNotes: r.oldCostNotes,
    costRefundAmount: r.additionalCostPrice,
    costRefundCurrency: r.additionalCostCurrency,
    costRefundRoe: r.additionalCostRoe,
    costRefundInr: r.additionalCostInr,
    costRefundNotes: r.additionalCostNotes,
    sellingprice: r.oldSellingPrice,
    sellingCurrency: r.oldSellingCurrency,
    sellingRoe: r.oldSellingRoe,
    sellingInr: r.oldSellingInr,
    sellingNotes: r.oldSellingNotes,
    sellingRefundAmount: r.additionalSellingPrice,
    sellingRefundCurrency: r.additionalSellingCurrency,
    sellingRefundRoe: r.additionalSellingRoe,
    sellingRefundInr: r.additionalSellingInr,
    sellingRefundNotes: r.additionalSellingNotes,
    vendorBasePrice: r.oldVendorBasePrice,
    vendorBaseCurrency: r.oldVendorBaseCurrency,
    vendorBaseRoe: r.oldVendorBaseRoe,
    vendorBaseInr: r.oldVendorBaseInr,
    vendorBaseNotes: r.oldVendorBaseNotes,
    vendorInvoiceRefundAmount: r.additionalVendorBasePrice,
    vendorInvoiceRefundCurrency: r.additionalVendorBaseCurrency,
    vendorInvoiceRefundRoe: r.additionalVendorBaseRoe,
    vendorInvoiceRefundInr: r.additionalVendorBaseInr,
    vendorInvoiceRefundNotes: r.additionalVendorBaseNotes,
    vendorIncentiveReceived: r.oldVendorIncentiveReceived,
    vendorIncentiveCurrency: r.oldVendorIncentiveCurrency,
    vendorIncentiveRoe: r.oldVendorIncentiveRoe,
    vendorIncentiveInr: r.oldVendorIncentiveInr,
    vendorIncentiveNotes: r.oldVendorIncentiveNotes,
    chargebackAmount: r.additionalVendorIncentive,
    chargebackCurrency: r.additionalVendorIncentiveCurrency,
    chargebackRoe: r.additionalVendorIncentiveRoe,
    chargebackInr: r.additionalVendorIncentiveInr,
    chargebackNotes: r.additionalVendorIncentiveNotes,
    commissionPaid: r.oldCommissionPaid,
    commissionCurrency: r.oldCommissionCurrency,
    commissionRoe: r.oldCommissionRoe,
    commissionInr: r.oldCommissionInr,
    commissionNotes: r.oldCommissionNotes,
    commissionRefundAmount: r.additionalCommissionPaid,
    commissionRefundCurrency: r.additionalCommissionCurrency,
    commissionRefundRoe: r.additionalCommissionRoe,
    commissionRefundInr: r.additionalCommissionInr,
    commissionRefundNotes: r.additionalCommissionNotes,
    sellingPrices: r.rescheduledSellingPrices?.map(
      (sp): SellingPriceEntry => ({
        sellingprice: sp.oldSellingPrice,
        sellingCurrency: sp.oldSellingCurrency,
        sellingRoe: sp.oldSellingRoe,
        sellingInr: sp.oldSellingInr,
        sellingNotes: sp.oldSellingNotes,
        sellingRefundAmount: sp.additionalSellingPrice,
        sellingRefundCurrency: sp.additionalSellingCurrency,
        sellingRefundRoe: sp.additionalSellingRoe,
        sellingRefundInr: sp.additionalSellingInr,
        sellingRefundNotes: sp.additionalSellingNotes,
      }),
    ),
  }) as AmountSectionValue;
